### PR TITLE
Timer Smart Contract

### LINKED ISSUE #133: Timer Smart contract
Timer  Smart Contract
(Write project title over here)

Timer smart Contract makes the contract work in a certain time period, after a certain period it completed it raises an error time over.
(Describe the project over here)

### Domain

- [x] Solidity

#### Are you contributing under any open-source program ?
yes, I am hactoberfest 2022 Contributor.

<hr/>

### PR DESCRIPTION
**Pull request by saikishore222**
## Timer Smart Contract is to access the function between a certain time period, the timer runs throughout the Contract , Once the timer ends, you cannot have access to Contract Functions.

Please include a summary of the change and which issue is fixed.

Fixes #133 

## Type of change

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this :

- [x] Add a new project

- [] Modified or enhanced the existing projects

- [] Improve the readme of any project

## Domain of Contribution

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] Project using only Solidity

- [x] Project Test on the Remix IDE

## Checklist ✓

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] l have performed a self-review of my own code or work.

- [x] I have commented on my code, particularly in hard-to-understand areas.

- [x] My changes generate no new warnings

I am Hactoberfest 2022 Contributor

## Screenshots/Gif (Recommended)

Compilation of the program.
image

deploy
image

image

### CODE REVIEW

**Comment by saikishore222** [comment]
@Vikash-8090-Yadav This PR is ready to Review. can you please review it??

**Comment by Vikash-8090-Yadav** [comment]
@saikishore222  please add this line in ur readme after  the   intro 

Note : If u don't know how to use Remix ide  you can read this https://github.com/Vikash-8090-Yadav/Solidity-Pathshala/blob/main/Blog/How%20to%20use%20remix%20IDE/How%20to%20use%20remix.ide.md

and if u are not familiar with the solidity then read from here https://github.com/Vikash-8090-Yadav/Solidity-Pathshala/tree/main/Study_Material

**Comment by Vikash-8090-Yadav** [comment]
> @saikishore222 please add this line in ur readme after the intro
> 
> Note : If u don't know how to use Remix ide you can read this https://github.com/Vikash-8090-Yadav/Solidity-Pathshala/blob/main/Blog/How%20to%20use%20remix%20IDE/How%20to%20use%20remix.ide.md
> 
> and if u are not familiar with the solidity then read from here https://github.com/Vikash-8090-Yadav/Solidity-Pathshala/tree/main/Study_Material

Make all this **BOLD**

**Comment by saikishore222** [comment]
@Vikash-8090-Yadav I updated Readme can you please review it again

**Comment by Vikash-8090-Yadav** [comment]
@saikishore222  Your codes Look clean and good 
Looking forward to see more contribution  from your side . 

Happy open source :smile:

**Pull request merged**
