### PR TITLE
Ashish kumar

### LINKED ISSUE #48: Some great Solidity tools and integrated environment to learn
### Project title
Some Solidity Tools to get started with 

### Project Description
To create a readme file for some great solidity tools and integration with examples which makes writing solidity easy and robust. 
### Domain

- [] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [] Other, feel free to mention below

#### Are you contributing under any open-source program?
SSOC
<hr/>

### PR DESCRIPTION
**Pull request by ASHISHKUMAR2411**
## Description

Some Solidity Tools to get started with

Fixes #48 

## Type of change

- [x] Add a new project

- [x] Improve the readme of any project

## Domain of Contribution

- [x] Project using only Solidity

- [x] Project Test on the Remix IDE

## Checklist ✓
- [x] l have performed a self-review of my own code or work.

- [x] My changes generate no new warnings

- [x] I'm SSOC'22 contributor

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
@ASHISHKUMAR2411  increase the font size and decrease the Image length . as this seems little messy  which makes hard to read .

**Comment by Vikash-8090-Yadav** [comment]
One last thing include all this in the Blog section and delete from the study material .
All look's great to me . 
Ready for merge after this .

**Comment by Vikash-8090-Yadav** [comment]
Update ur branch to the latest

**Comment by Vikash-8090-Yadav** [comment]
@ASHISHKUMAR2411  any updates ? . Let me know  if  u are facing issue in the any git command . 
Thank u

**Comment by ASHISHKUMAR2411** [comment]
Yes I am not able to update my branch, I tried but my repository doesn't look the same as your
I used git fetch

**Comment by ASHISHKUMAR2411** [comment]
Please check for the updated branch

**Comment by Vikash-8090-Yadav** [comment]
Great @ASHISHKUMAR2411

**Pull request merged**
