### PR TITLE
Counter Contract

### LINKED ISSUE #108: Create a Counter Smart Contract Program
Smart Contract Program
(Write project title over here)

The owner of the smart contract able to Increase the Counter value and decrease the Counter value in the contract
(Describe the project over here)

### Domain

- [x] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [] Other, feel free to mention below

#### Are you contributing under any open-source program ?
Yes ,Hacktoberfest 2022

<hr/>

### PR DESCRIPTION
**Pull request by saikishore222**
##Counter Smart Contract, Owner can Increment and decrement the Count value and get the Count value

Please include a summary of the change and which issue is fixed.

Fixes #108 

## Type of change

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this :

- [x] Add a new project

## Domain of Contribution

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] Project using only Solidity

- [x] Project Test on the Remix IDE

## Checklist ✓

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] l have performed a self-review of my own code or work.

- [x] I have commented on my code, particularly in hard-to-understand areas.

- [x] My changes generate no new warnings

Iam Hactoberfest Contributor

## Screenshots/Gif (Recommended)
compilation code

Screenshot from 2022-10-01 17-16-15

Deploy and Run

image

### CODE REVIEW

**Comment by saikishore222** [comment]
@Vikash-8090-Yadav  The PR is ready for review

**Comment by Vikash-8090-Yadav** [comment]
@saikishore222  update ur branch to the latest

**Comment by saikishore222** [comment]
You mean I have to change branch name

**Comment by saikishore222** [comment]
> @saikishore222  update ur branch to the latest 

Ok

**Comment by saikishore222** [comment]
> @saikishore222 update ur branch to the latest

I updated the branch @Vikash-8090-Yadav  could you please review it.

**Comment by Vikash-8090-Yadav** [comment]
@saikishore222  Great Work . Looking forward for your more contribution .

**Pull request merged**
