### PR TITLE
Added Decentralized Bingo Game

### LINKED ISSUE #165: Decentralized Bingo
### Project title
Decentralized Bingo Game

### Project Description
This is a Decentralized Bingo Game

it contains two files
1- Voting and
2- Bingo

While The Bingo file is responsible for the Details of the 5x5 card and striking out
Voting maintains the round and voting of which number to strike out

- [x] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [] Other, feel free to mention below

<hr/>

### PR DESCRIPTION
**Pull request by Source-404**
## Description

This is a Decentralized Bingo Game

it contains two files
1- Voting and
2- Bingo

While The Bingo file is responsible for the Details of the 5x5 card and striking out
Voting maintains the round and voting of which number to strike out

Fixes #165 

## Type of change

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this :

- [x] Add a new project

- [] Modified or enhanced the existing projects

- [] Improve the readme of any project

## Domain of Contribution

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] Project using only Solidity

- [] Project using only Javascript

- [] Project using only Python

- [x] Project Test on the Remix IDE

- [] Mention below if project uses other language and ide .

## Checklist ✓

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] l have performed a self-review of my own code or work.

- [x] I have commented on my code, particularly in hard-to-understand areas.

- [x] My changes generate no new warnings

- [] I'm HSOC'22 contributor

- [] I'm SSOC'22 contributor

## Screenshots/Gif (Recommended)

image

image

(Screenshot taken from Remix IDE)

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
@Source-404 please add the Readme file

**Comment by Source-404** [comment]
@Vikash-8090-Yadav i added the Readme file

**Comment by Source-404** [comment]
@Vikash-8090-Yadav Please review My PR

**Comment by Vikash-8090-Yadav** [comment]
Add something about bingo in the readme explains the major function and their work in the readme .

**Comment by Source-404** [comment]
@Vikash-8090-Yadav i have added all the information, can u please review and merge as today is the last day for hacktoberfest.

**Comment by Vikash-8090-Yadav** [comment]
Great ..

**Comment by Source-404** [comment]
@Vikash-8090-Yadav Thank you very much

**Pull request merged**
