### PR TITLE
added faucet smart contract

### LINKED ISSUE #100: Faucet Smart Contract
I want to create a faucet smart contract for a custom ERC20 token giving a fixed amount of tokens to the address requested it after a specific interval of time.
I would have to create two contracts one for the token and the other for the faucet smart contract.

Can I work on this? @Vikash-8090-Yadav

### PR DESCRIPTION
**Pull request by nirban256**
## Description

Added readme and Faucet.sol files for the faucet app

Fixes #100 

## Type of change

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this :

- [] Add a new project

- [] Improve the readme of any project

## Domain of Contribution

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [] Project using only Solidity

## Checklist ✓

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [] l have performed a self-review of my own code or work.

- [] My changes generate no new warnings

## Screenshots/Gif (Recommended)

Screenshot (20)

### CODE REVIEW

**Comment by nirban256** [comment]
@Vikash-8090-Yadav  review it once

**Comment by Vikash-8090-Yadav** [comment]
@nirban256 i ll do by eod .Currently am in class rn .

**Comment by Vikash-8090-Yadav** [comment]
Add  the image of the  code and also explains  some function and their works.  All this should be done in readme 
@nirban256  hope u  understand .

**Comment by nirban256** [comment]
@Vikash-8090-Yadav if I add a video containing the whole process will it be ok?

**Comment by nirban256** [comment]
@Vikash-8090-Yadav review it once

**Comment by Vikash-8090-Yadav** [comment]
Great @nirban256  . Looking  forward for your more contribution from  your side .

**Pull request merged**
