### PR TITLE
Creation of a wallet with advanced functionalities

### LINKED ISSUE #47: Creating a Wallet with various useful functions
### Project title
Creating a wallet  

### Project Description
With the help of which a user can 
1> deposit ether to his wallet ,
2> send ether to another account and 
3> check his own ether account balance.

This also comes with various restrictions imposed like only the owner can transfer ether to the reciever which is much needed in this case.
### Domain

- [x] Solidity

#### Are you contributing under any open-source program ?
SSOC22
<hr/>

### PR DESCRIPTION
**Pull request by legendarykamal**
## Description
A Wallet with many features.

This PR fixes #47 

These functionalities have been implemented in this contract.

1> Creation of a public payable state variable by the name of owner to store the address of the owner.

2> constructor ( ) - It will take one argument to initialise the owner of the contract.

3> deposit ( ) - To deposit ether to contract balance.

4> sendEther ( ) - It will take two arguments. First the address of the receiver to whom we want to send the amount to. Second the amount(uint) that we want to send.

    a) This function must be called by the owner of the contract. Otherwise, it should print "sender is not allowed". [Hint - Use require]

    b) If the owner of the contract has called this function then transfer the ether to the receiver's address.

5> balanceOf ( ) - To return the balance of the contract

Fixes #47

## Type of change

- [x] Add a new project

## Domain of Contribution

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] Project using only Solidity

- [] Project using only Javascript

- [] Project using only Python

- [x] Project Test on the Remix IDE

## Checklist ✓

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] l have performed a self-review of my own code or work.

- [x] I have commented on my code, particularly in hard-to-understand areas.

- [x] I'm SSOC'22 contributor

### CODE REVIEW

**Comment by legendarykamal** [comment]
@Vikash-8090-Yadav please review this

**Comment by Vikash-8090-Yadav** [comment]
@legendarykamal   update the branch to the latest

**Comment by Vikash-8090-Yadav** [comment]
@legendarykamal  update the image according to the newest

**Comment by legendarykamal** [comment]
> @legendarykamal update the branch to the latest

that shall have no effect on this PR as these are fresh additions to the file.

**Comment by legendarykamal** [comment]
@Vikash-8090-Yadav updated the latest images :+1:

**Comment by Vikash-8090-Yadav** [comment]
Ur branch  is 9 commits behind update to the latest

**Comment by legendarykamal** [comment]
@Vikash-8090-Yadav done updated to the latest

**Comment by Vikash-8090-Yadav** [comment]
@legendarykamal move this to the level 1 folder ,

**Comment by legendarykamal** [comment]
@Vikash-8090-Yadav done

**Comment by Vikash-8090-Yadav** [comment]
Update your branch to the latest .

**Comment by legendarykamal** [comment]
done

**Comment by Vikash-8090-Yadav** [comment]
Again update ur branch to the latest . ALl set to merge then,
@legendarykamal

**Comment by Vikash-8090-Yadav** [comment]
@legendarykamal  ?? any updates

**Comment by legendarykamal** [comment]
yes done @Vikash-8090-Yadav sorry for the late reply mid semester's going on  :+1:

**Comment by Vikash-8090-Yadav** [comment]
Great work @legendarykamal  .

**Pull request merged**
