### PR TITLE
freelancer smart contract

### LINKED ISSUE #161: Freelancer smart contract
it has three functions:

Employer deposit eth in smart contract, deposit().
Freelancer upload data, like a link with his work, upload().
Withdraw ether. withdraw(). 

Please assign this to me . i want to work on this . 
Thanks

### PR DESCRIPTION
**Pull request by suyashmadhesia**
### added three files
* Freelancer.sol for the freelancer smart contract
* readme.md explaining the code in brief
* Screenshot of the remix IDE of deployed contract.

## ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
include the running video in the readme

**Comment by suyashmadhesia** [comment]
@Vikash-8090-Yadav where should I upload that video as a proof or in readme?

**Comment by Vikash-8090-Yadav** [comment]
> @Vikash-8090-Yadav where should I upload that video as a proof or in readme?

upload that video in the readme . at  the last

**Comment by suyashmadhesia** [comment]
@Vikash-8090-Yadav can you please check I have uploaded the video regarding the video for the woking of the smart contract

**Pull request merged**
