### PR TITLE
Fixed issue #27

### LINKED ISSUE #27: Adding comment in the Hello world solidity file
### Description of  the change
Some things like view and memory keywords need to be clear for a person looking at the code for the first time.

### Domain 
- [x] Solidity

#### Are you contributing under any open-source program ?

SSOC

### PR DESCRIPTION
**Pull request by TripathiShyaamal**
## Description

Included some comments for better understanding in the Level0 directory codes for better understanding of beginners.

Fixes #27

## Type of change

- [x] Modified or enhanced the existing projects

## Domain of Contribution

- [x] Project using only Solidity

## Checklist ✓

- [x] I have commented on my code, particularly in hard-to-understand areas.

- [x] I'm SSOC'22 contributor

## Screenshots/Gif (Recommended)
Greeting
HelloWorld

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
@TripathiShyaamal can u please tell what u have  done  in this ? or what improvement done by u ?

**Comment by TripathiShyaamal** [comment]
For a complete beginner the version pragma will not be understandable so I added comment about that and also about the view, public, constructor and public function so that every line of code is clear to understand.

**Comment by Vikash-8090-Yadav** [comment]
> For a complete beginner the version pragma will not be understandable so I added comment about that and also about the view, public, constructor and public function so that every line of code is clear to understand.

@TripathiShyaamal  ya it's fine i checked but u r also pushing the metadata and abi , bytte code along  with this please check this one and correct

**Comment by Vikash-8090-Yadav** [comment]
@TripathiShyaamal please ping me  when updating completed .

**Comment by TripathiShyaamal** [comment]
@Vikash-8090-Yadav I updated the files, kindly check.

**Comment by Vikash-8090-Yadav** [comment]
> @Vikash-8090-Yadav I updated the files, kindly check.

@TripathiShyaamal am not seeing .sol where is it ?

**Comment by Vikash-8090-Yadav** [comment]
@TripathiShyaamal  got it .. Thanks  for this P.R looking  forward to see more contribution from your side  . 
Thank u

**Pull request merged**
