### PR TITLE
Create P.R template #3

### LINKED ISSUE #3: Create P.R template
Greetings of the day folks !!
If anyone want's to create the issue template then feel free to comment
The template should look like this  shown below 

Screenshot from 2022-07-25 18-06-45

### PR DESCRIPTION
**Pull request by surjyaneeh**
## Description

Created P.R. Template

Fixes #3 

## Type of change

- [x] Improve the readme of any project

## Checklist ✓

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] l have performed a self-review of my own code or work.

- [x] I have commented on my code, particularly in hard-to-understand areas.

- [x] My changes generate no new warnings

- [x] I'm HSOC'22 contributor

### CODE REVIEW

**Comment by surjyaneeh** [comment]
@Vikash-8090-Yadav can you please check it and let me know if it needs any changes.

**Comment by Vikash-8090-Yadav** [comment]
> @Vikash-8090-Yadav can you please check it and let me know if it needs any changes.


Your branch is 5 commits ahead from main 
just do **git pull** and then again submit the P.R

**Comment by surjyaneeh** [comment]
> > @Vikash-8090-Yadav can you please check it and let me know if it needs any changes.
> 
> Your branch is 5 commits ahead from main just do **git pull** and then again submit the P.R

Should I close this PR and make a new one?

**Comment by Vikash-8090-Yadav** [comment]
> > > @Vikash-8090-Yadav can you please check it and let me know if it needs any changes.
> > 
> > 
> > Your branch is 5 commits ahead from main just do **git pull** and then again submit the P.R
> 
> Should I close this PR and make a new one?

Yah ,sure u can

**Pull request closed without merging**
