### PR TITLE
Storing Books

### LINKED ISSUE #127: Books DB
### Project title
Setting and Getting Books 

### Project Description
I wish to create a smart contract using which we will be able to store books with their title, author's name and id and then later on we can get the books using its id.

### Domain

- [x] Solidity

#### Are you contributing under any open-source program ?
- [x] Hacktoberfest 2022
<hr/>

### PR DESCRIPTION
**Pull request by vryan-06**
## Description

Here I am adding a folder Storing Books which will store and retrieve the data of the books.

Fixes #127  

## Type of change

- [x] Add a new project

## Domain of Contribution

- [x] Project using only Solidity

## Checklist ✓

- [x] l have performed a self-review of my own code or work.

- [x] I have commented on my code, particularly in hard-to-understand areas.

- [x] My changes generate no new warnings

- [x] I'm Hacktoberfest22 contributor

## Screenshots/Gif (Recommended)

Screenshot (1137)
<br><br>

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Write brief intro about the Storing books in the  readme .

**Comment by vryan-06** [comment]
Done @Vikash-8090-Yadav

**Comment by vryan-06** [comment]
Let me know if any further changes are required. @Vikash-8090-Yadav

**Comment by Vikash-8090-Yadav** [comment]
Hey @vryan-06  Thnak u fory our patience . 
Everythings looks  great to  me .

**Pull request merged**
