### PR TITLE
Make changes as per the work assigned

### LINKED ISSUE #183: FIR smart contract
### Project title
FIR smart contract

### Project Description
I wish to add a smart contract for FIR system to the repo as a contribution for the community to learn real life usage of smart contracts

### Domain

- [x] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [] Other, feel free to mention below

#### Are you contributing under any open-source program?
yes
fir

<hr/>

### PR DESCRIPTION
**Pull request by apoorva1823000**
## Description

Updated the voting solidity smart contract folder in the level 2 of this repo as well as added FIR smart contract and its description readme file in the level 1

Fixes #183 and #176

## Type of change

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this :

- [x] Add a new project

- [x] Modified or enhanced the existing projects

- [x] Improve the readme of any project

## Domain of Contribution

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] Project using only Solidity

- [] Project using only Javascript

- [] Project using only Python

- [x] Project Test on the Remix IDE

- [] Mention below if project uses other language and ide .

## Checklist ✓

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] l have performed a self-review of my own code or work.

- [x] I have commented on my code, particularly in hard-to-understand areas.

- [x] My changes generate no new warnings

- [] I'm HSOC'22 contributor

- [x] I'm SSOC'22 contributor

## Screenshots/Gif (Recommended)
fir
ss4

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
@apoorva1823000  put running video at the last of  the readme of both files  .

**Comment by Vikash-8090-Yadav** [comment]
All thing's are looking fine , replace  the last image with the running video . in both  Readme files . Hope u get this

**Review by apoorva1823000 — COMMENTED** [review]
Added short videos

**Comment by apoorva1823000** [comment]
> All thing's are looking fine , replace the last image with the running video . in both Readme files . Hope u get this

@Vikash-8090-Yadav added the video but kindly review if its showing or not

**Comment by Vikash-8090-Yadav** [comment]
Thanks for this changements .Now looking gr8

**Pull request merged**
