### PR TITLE
added emergency stop code

### LINKED ISSUE #144: add emergency stop
hi i want to add emergency stop. kindly assign this issue to me.

### PR DESCRIPTION
**Pull request by syashu16**
## Description

Please include a summary of the change and which issue is fixed.

Fixes #144 

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this :

- [x] Add a new project

- [] Modified or enhanced the existing projects

- [] Improve the readme of any project

## Domain of Contribution

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

  - [x] Project using only Solidity
  
  - [x] Project using only Javascript
  

## Checklist ✓

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [] l have performed a self-review of my own code or work.

- [] I have commented on my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
@syashu16 Please  correct the grammatical  mistakes in the readme.md file

**Comment by syashu16** [comment]
@Vikash-8090-Yadav please review this . i had corrected the mistakes.

**Comment by Vikash-8090-Yadav** [comment]
@syashu16   . This looks great to me . 
U r code is clean and nice . Looking forward to see more contribution from your side .
Happy  opensource . 

:smile:

**Comment by syashu16** [comment]
> @syashu16 . This looks great to me . U r code is clean and nice . Looking forward to see more contribution from your side . Happy opensource .
> 
> 😄

thank you sirji 😀

**Pull request merged**
