### PR TITLE
Added 4 codes

### PR DESCRIPTION
**Pull request by vryan-06**
**Issue Number #34**

Wrote 4 solidity codes.

## Description

According to the instructions provided on Discord, I have added 4 simple codes in the Level0 folder as a trial since this is my first github contribution.

## Type of change

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this :

- [x] Added 4 new solidity codes

- [x] Added the readme files to the codes

## Domain of Contribution

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] Project using only Solidity

## Checklist ✓

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] l have performed a self-review of my own code or work.

- [x] l have added comments wherever it was necessary in the code.

- [x] My changes generate no new warnings

- [x] I'm SSOC'22 contributor

## Screenshots/Gif (Recommended)

image

image

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Hey bro thanks for this .. But before raising P.R  i would suggest u to raise a issue first then i will assign u .Then u can raise a P.R .
Thank u .
 Don't delete this P.R  just  link  that issue to this P.R when   i will assign u  
Thank u :smile:

**Comment by vryan-06** [comment]
Sorry, I had no idea. 
Thanks a lot though, I have raised a new issue now.

**Comment by Vikash-8090-Yadav** [comment]
@vryan-06  include that no number  in this pr by **#(issue no)** 

Also add the readme.md for every file as done in the Hello world in the level0 folder . 
Thank u

**Comment by vryan-06** [comment]
Hi,
I have updated the readme files accordingly and also added the issue number. 
Kindly check and let me know.

**Comment by Vikash-8090-Yadav** [comment]
Great @vryan-06 .Looking forward for your more contribution. ✌️🤘

**Pull request merged**
