### PR TITLE
Fixed issue #46

### LINKED ISSUE #46: Notes on Solidity from Loom Network
I will create a seperate file named Solidity_Notes and add the solidity notes there itself.

### PR DESCRIPTION
**Pull request by TripathiShyaamal**
## Description

Added the Notes in the Study Material Folder. 

Fixes #46 

## Type of change

- [x] Add a new project

## Domain of Contribution

- [x] Project using only Solidity

## Checklist ✓

- [x] My changes generate no new warnings

- [x] I'm SSOC'22 contributor

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Can u just do one thing  write all the thing;s present in docs' in the reamde.md(make a new folder for this in study_material) and then at the last just put that word file . 
Let me know if u r facing any problem

**Comment by Vikash-8090-Yadav** [comment]
@TripathiShyaamal

**Comment by TripathiShyaamal** [comment]
I'll do that

**Comment by TripathiShyaamal** [comment]
Should the file structure be like this: Study_Material -> New Folder -> Readme and Docs   ?

**Comment by Vikash-8090-Yadav** [comment]
@TripathiShyaamal  nope create a folder like this - >  Study_Material / Solidity_Basics/Images,Readme.md

**Comment by TripathiShyaamal** [comment]
Okay so the original doc content will be in the Readme and Images folder for the code snippets in the doc right ?

**Comment by Vikash-8090-Yadav** [comment]
> Okay so the original doc content will be in the Readme and Images folder for the code snippets in the doc right
Ok make it simple just forget about IMage folder continue wirh the readme and Doc

**Comment by TripathiShyaamal** [comment]
Hey @Vikash-8090-Yadav,

The problem is that the images are not getting displayed in the Readme file because I will have to upload all the images on github or somewhere but the thing is the images are many and also I had pasted the ss of those images and they are not saved anywhere so is there any other way ?

**Comment by Vikash-8090-Yadav** [comment]
> Hey @Vikash-8090-Yadav,
> 
> The problem is that the images are not getting displayed in the Readme file because I will have to upload all the images on github or somewhere but the thing is the images are many and also I had pasted the ss of those images and they are not saved anywhere so is there any other way ?

Try drag and drop  .. Let me know if u r still facing the same issue

**Pull request closed without merging**
