### PR TITLE
Real time data feed of ETH/USD using chainlink

### LINKED ISSUE #102: Getting real time data feeds  in  smart contract with Chainlink
Hii sir , please assign this issue to me , 
In this i want create a smart contract   which can get     the real time data feeds  with the help of the  chainLink  API . 

The folder structure is ; Level1/Chainlink/RealTimedata.sol

### PR DESCRIPTION
**Pull request by test-account09**
## Description

In this i want create a smart contract which can get the real time data feeds with the help of the chainLink API .

Fixes #102 

## Type of change

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this :

- [x] Add a new project

## Domain of Contribution

- [x] Project using only Solidity

- [x] Project Test on the Remix IDE

## Checklist ✓

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] l have performed a self-review of my own code or work.

- [x] I have commented on my code, particularly in hard-to-understand areas.

- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
@test-account09 please update the readme also . U can check the format of the reamde . By reading contributing guidelines . Let me know if u face any issue .

**Comment by test-account09** [comment]
@Vikash-8090-Yadav  u can review this .

**Comment by Vikash-8090-Yadav** [comment]
Readme looks good .but do one thing  add comments in your code also for better understanding .@test-account09

**Comment by test-account09** [comment]
Sure sir @Vikash-8090-Yadav

**Comment by Vikash-8090-Yadav** [comment]
Great @test-account09..

**Pull request merged**
