### PR TITLE
Basic banking 

### LINKED ISSUE #162: Basic banking
hey , i want to create  the function that  create  the basics of the banking system like , Transfer , withdraw  ,and many more . 
please assign this to me so that i can start contributing  on this . 
Thanks in advance .

### PR DESCRIPTION
**Pull request by Omega12Pirme**
## Description

I have created a new file named BasicBanking in  which user can create his/her account and etc .

Fixes #162 

- [] Add a new project

- [x] Modified or enhanced the existing projects

- [x] Improve the readme of any project

## Domain of Contribution

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] Project using only Solidity

- [x] Project Test on the Remix IDE

## Checklist ✓

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] l have performed a self-review of my own code or work.

- [x] I have commented on my code, particularly in hard-to-understand areas.

- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Omega12Pirme** [comment]
@Vikash-8090-Yadav  please check this once and let me know . if u needed any further changes .

**Comment by Vikash-8090-Yadav** [comment]
@Omega12Pirme  please add the readme for the project

**Comment by Omega12Pirme** [comment]
@Vikash-8090-Yadav  please  take a look

**Comment by Vikash-8090-Yadav** [comment]
Your code seems  clean and great  . Looking forward to see more contribution from your side .

**Pull request merged**
