### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by RiddhiRaj**
Corrected few spellings and trimmed spaces 

- [x] Improve the readme of this project

image

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Great work @RiddhiRaj  . but as u r correcting only the few word  so a/c to the ssoc pr guidelines i am giving  u 5 marks outof 10 in beginner level . @AnmolSirola  please  note this

**Comment by RiddhiRaj** [comment]
Hey @Vikash-8090-Yadav thanks a lot for merging my pull request. This was my 1st. I am a beginner and I'm looking to contribute more! Thanks!

**Comment by Vikash-8090-Yadav** [comment]
ya @RiddhiRaj there are lot's of things to be kept in mind while contributing . 

1. always make Issue before the P.R 
2. Don't make p.r untill the owner assign u that issue , 
All  things are fine but kept this in your mind  while contributing in the future  . 
Thank u @RiddhiRaj for contributing in my project . 
Looking forward to see more contribution from your side .

**Comment by Vikash-8090-Yadav** [comment]
U r contributing under ssoc'22 programme right ?

**Comment by RiddhiRaj** [comment]
> ya @RiddhiRaj there are lot's of things to be kept in mind while contributing .
> 
> 1. always make Issue before the P.R
> 2. Don't make p.r untill the owner assign u that issue ,
>    All  things are fine but kept this in your mind  while contributing in the future  .
>    Thank u @RiddhiRaj for contributing in my project .
>    Looking forward to see more contribution from your side .

Absolutely. Will keep that in mind. Currently I am learning MERN and will then move forward to learn Solidity.

And no, I'm not contributing under ssoc'22 program. I did it independently. I'm sorry, is that a problem?

**Pull request merged**
