### PR TITLE
Create ifelse

### PR DESCRIPTION
**Pull request by adielliot37**
## Description

Please include a summary of the change and which issue is fixed.

Fixes #<issue_number_here>

## Type of change

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this :

- [] Add a new project

- [] Modified or enhanced the existing projects

- [] Improve the readme of any project

## Domain of Contribution

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [] Project using only Solidity

- [] Project using only Javascript

- [] Project using only Python

- [] Project Test on the Remix IDE

- [] Mention below if project uses other language and ide .

## Checklist ✓

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [] l have performed a self-review of my own code or work.

- [] I have commented on my code, particularly in hard-to-understand areas.

- [] My changes generate no new warnings

- [] I'm HSOC'22 contributor

- [] I'm SSOC'22 contributor

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
I guess this  project is already there is my  repo .

**Comment by adielliot37** [comment]
please check again i think it isnt

**Comment by Vikash-8090-Yadav** [comment]
check this issue #39 , 
Already assign to someone . 
Hope u understand .

**Comment by adielliot37** [comment]
ok i will add another one

**Comment by Vikash-8090-Yadav** [comment]
am closing this pr .Before raising pr its Obvious that u should raise issue 1st

**Pull request closed without merging**
