### PR TITLE
Solved issue #208

### PR DESCRIPTION
**Pull request by prakhar3062**
## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
issue no?

**Comment by prakhar3062** [comment]
Allowance management wallet #208

**Comment by Vikash-8090-Yadav** [comment]
@prakhar3062 make the readme in the proper format , else everything is good !

**Comment by Vikash-8090-Yadav** [comment]
Great

**Pull request merged**
