### PR TITLE
New readme.md file for level 1 folder and all the grammatical errors solved.

### PR DESCRIPTION
**Pull request by AnmolSirola**
## Description

New readme.md file for sendTo_ether (level 1 folder created  )and all the grammatical errors were corrected.

Fixes #<20>

## Type of change

- [x] Modified or enhanced the existing projects

- [x] Improve the readme of any project

## Domain of Contribution

- [x] Project using only Solidity

- [x] Project Test on the Remix IDE

## Checklist ✓

- [] I'm SSOC'22 contributor

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
@AnmolSirola  refer the style of the writing readme from level0 Folder ..

**Comment by AnmolSirola** [comment]
Okay Sir working on it

**Comment by AnmolSirola** [comment]
Sir, can u check it now.

**Comment by Vikash-8090-Yadav** [comment]
Great work @AnmolSirola Hoping the another Great issue  from your side 
Thank u

**Pull request merged**
