### PR TITLE
create TimeLock.sol

### PR DESCRIPTION
**Pull request by Aman5989**
A TIME LOCKED WALLET

## Description

Please include a summary of the change and which issue is fixed.

Fixes #<issue_number_here>

## Type of change

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this :

- [x] Add a new project

## Domain of Contribution

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] Project using only Solidity

## Checklist ✓

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] l have performed a self-review of my own code or work.

### CODE REVIEW

**Comment by Aman5989** [comment]
Please add hacktoberfest tags

**Comment by Vikash-8090-Yadav** [comment]
Have u raised an issue before rasing pr ?

**Comment by Aman5989** [comment]
i have raised it right now.

**Comment by Vikash-8090-Yadav** [comment]
@Aman5989 please create a readme for this also

**Comment by Aman5989** [comment]
sure but please merge this PR so that a folder would be created

**Comment by Vikash-8090-Yadav** [comment]
Add comments in your code @Aman5989

**Pull request closed without merging**
