### PR TITLE
Erc20 token contract

### PR DESCRIPTION
**Pull request by shobhit9070**
## Description

Created the erc20 contract which help the user to create its own tokens  and display them on metamask.
- [x] Add a new project

## Domain of Contribution

- [x] Project using only Solidity
- [x] Project Test on the Remix IDE

## Checklist ✓

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] l have performed a self-review of my own code or work.
- [x] My changes generate no new warnings
- [x] I'm HSOC'22 contributor

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
@shobhit9070 have u created the Issue for this ?

**Comment by shobhit9070** [comment]
sorry i forgot to change the name of the pr.

**Comment by shobhit9070** [comment]
@Vikash-8090-Yadav can you see this once?

**Comment by Vikash-8090-Yadav** [comment]
NO , u  not getting , Am just asking have u created the  issue earlier for this or u raised direct PR ?

**Comment by shobhit9070** [comment]
@Vikash-8090-Yadav  yes i have created the issue earlier.

**Comment by Vikash-8090-Yadav** [comment]
If u are raising PR its mandatory to include the issue no like this . #136  .Anyways don't do this mistake again
Hope   u understand

**Comment by Vikash-8090-Yadav** [comment]
@shobhit9070  please add some comment in the code .

**Comment by shobhit9070** [comment]
@Vikash-8090-Yadav  okay sure will keep this in mind

**Comment by shobhit9070** [comment]
@Vikash-8090-Yadav  can you check once .. 
hope you don't mind the mistake.. i am new to the space

**Comment by Vikash-8090-Yadav** [comment]
> @Vikash-8090-Yadav can you check once .. hope you don't mind the mistake.. i am new to the space

Ya learning comes from the mistakes only . Everyone is equal in open source,
 don't worry !  
😃

**Comment by Vikash-8090-Yadav** [comment]
All looks great to me . Thanks for contributing in my repo . 
Loved to see more contribution from your side . 
Happy open source 😃

**Pull request merged**
