### PR TITLE
coin modified

### LINKED ISSUE #42: Adding a new feature
### Description of  the change

Currently https://github.com/Vikash-8090-Yadav/Solidity-Pathshala/tree/main/Level1/Coin allows only owner to mint coin.

We can add a feature for 
1> anybody to mint 
2> putting restrictions on the number of coins to be minted.

### Domain 

- [x] Readme
- [x] Solidity
- [] Python
- [] JavaScript
- [] Golang
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
SSOC22
<hr/>

### PR DESCRIPTION
**Pull request by legendarykamal**
## Description

Please include a summary of the change and which issue is fixed.

Fixes #42 

## Type of change
Modified the coin.sol and added the new features.
Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this :

- [] Add a new project

- [x] Modified or enhanced the existing projects

- [] Improve the readme of any project

## Domain of Contribution

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [] Project using only Solidity

- [] Project using only Javascript

- [] Project using only Python

- [] Project Test on the Remix IDE

- [] Mention below if project uses other language and ide .

## Checklist ✓

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] l have performed a self-review of my own code or work.

- [x] I have commented on my code, particularly in hard-to-understand areas.

- [x] My changes generate no new warnings

- [] I'm HSOC'22 contributor

- [x] I'm SSOC'22 contributor

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
@legendarykamal please describe what   the changes  you have done in the code

**Comment by legendarykamal** [comment]
yes @Vikash-8090-Yadav I have described it in contract as well as in the readme.
In contract you can find the lines ending with (**) as the modified ones.

**Comment by Vikash-8090-Yadav** [comment]
@legendarykamal  made more chnages  in  the readme fro the other files tooo. Cuz a/c to guidelines I can not give u beginner score only for this .. Hope u understand

**Comment by legendarykamal** [comment]
ok I will make thanks for the confirmation.

**Comment by legendarykamal** [comment]
@Vikash-8090-Yadav I have made 3 readme changes and 2 contract changes in total. 
I think this should be enough ?

**Comment by legendarykamal** [comment]
This also solves -> https://github.com/Vikash-8090-Yadav/Solidity-Pathshala/issues/44

**Comment by Vikash-8090-Yadav** [comment]
Great @legendarykamal

**Comment by legendarykamal** [comment]
thanks @Vikash-8090-Yadav

**Pull request merged**
