### PR TITLE
ERC-20 Upgradable Smart Contract

### LINKED ISSUE #140: ERC20 Upgradable Smart Contract
### Project title
ERC-20 Upgradable Smart Contract

### Project Description
Build a ERC20 Upgradable contract that can be (kind of) altered, after the deployment.

### Domain

- [x] Solidity
- [x] JavaScript
- [x] Hardhat

#### Are you contributing under any open-source program ?

Hacktoberfest 2022

<hr/>

### PR DESCRIPTION
**Pull request by Envoy-VC**
## Description

Added ERC-20 Upgradable Smart Contract Tutorial and Project Files.

Fixes #140 

## Type of change

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this :

- [x] Add a new project.

## Domain of Contribution

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] Project using Solidity and Hardhat.

## Checklist ✓

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] l have performed a self-review of my own code or work.

- [x] My changes generate no new warnings

- [x] I'm HSOC'22 contributor.

## Screenshots/Gif (Recommended)

IDE Screenshot

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
@Envoy-VC  please  include  working video in the readme along  with the intro of the project ,

**Comment by Envoy-VC** [comment]
Video will be done as soon as possible, what kind of intro are we looking for?

**Comment by Vikash-8090-Yadav** [comment]
> Video will be done as soon as possible, what kind of intro are we looking for?

Intro about this project , Which probelm is being solved by this project and add all this at the top under the heading "About" 
If already exsist make sure that is of 6-7 lines and also  under the "About" . 
Hope u understand

**Comment by Envoy-VC** [comment]
@Vikash-8090-Yadav Hey Can you check now, I have done things as you said,

**Comment by Vikash-8090-Yadav** [comment]
Excellent .Your code looks great and nice.You have written the clean code with comment s which makes user to better understand .
Thanks for contributing in my project 
.Happy open source ☺️

**Pull request merged**
