### PR TITLE
auction Contract

### LINKED ISSUE #112: Auction Price Smart Contract
### Project title
Auction Price Smart Contract

### Project Description
Auction Contract is allows to people to place bids,withdraw their funds of winning bid. owner of the auction can cancel the auction anytime.

### Domain

- [x] Solidity

#### Are you contributing under any open-source program ?
yes Iam hactoberfest Contributor

<hr/>

### PR DESCRIPTION
**Pull request by saikishore222**
Auction Smart Contract , it allows users to bid at a certain period of time ,after that auction ends, after auction ends , Amount will be transfer to highest bid contract

Please include a summary of the change and which issue is fixed.

Fixes #112 

## Type of change

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this :

- [x] Add a new project

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] Project using only Solidity

- [x] Project Test on the Remix IDE

## Checklist ✓

Please delete options that are not relevant. In order to tick the check box just put x inside them for example `[x]` like this

- [x] l have performed a self-review of my own code or work.

- [x] I have commented on my code, particularly in hard-to-understand areas.

- [x] My changes generate no new warnings

I am Hactoberfest 2022 Contributor

## Screenshots/Gif (Recommended)
Compilation with zero warnings

image

Deploying smart Contract

image

bidding:

image

### CODE REVIEW

**Comment by saikishore222** [comment]
@Vikash-8090-Yadav  The PR is ready to review .

**Comment by saikishore222** [comment]
> Write brief introduction in the readme about the Auction smart contract

Updated Reamde . Can you e Review it Again @Vikash-8090-Yadav

**Comment by Vikash-8090-Yadav** [comment]
@saikishore222   where did u write the brief intro ? can u please tell the line number .

**Comment by Vikash-8090-Yadav** [comment]
Hmm done . @saikishore222  .
Look's great to me  , Your code looks clean and clear . 
Happy  Open source :smile:

**Pull request merged**
