### PR TITLE
New readme.md files + grammatical erros corrected

### PR DESCRIPTION
**Pull request by AnmolSirola**
## Description

New readme.md files of Level 0 (Greetings , Hello World) ,Level 1(SendToEther) and Level 2 (Banking, Voting, Marketplace). Also corrected tons of grammatical errors ( inside SendtoEther , Banking and Voting smart contracts.)

Fixes #<11>

## Type of change
 New readme.md files added and grammatical were errors solved.

- [x] Modified or enhanced the existing projects

- [x] Improve the readme of any project

## Domain of Contribution

- [x] Project using only Solidity

- [x] Project Test on the Remix IDE

## Checklist ✓

- [x] I'm SSOC'22 contributor

## Screenshots

Readme.md

readme

read me lvl 1

readme lvl2

Few Errors many grammatical errors were inside code too:-

error 1

error 2

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
I am closing this P.R as somebosy has already added the readme for the Greeting.sol and other .. Raise a fresh P.R for Level 2 with grammatical error @AnmolSirola

**Comment by Vikash-8090-Yadav** [comment]
@AnmolSirola  ALso delete that issue and create fresh  one . Thank u

**Comment by AnmolSirola** [comment]
Okay Sir , I will solve the grammatical issues .Also in readme.md files are still missing from lvl 1 and lvl 2 folders can I raise an issue for them ?

**Comment by AnmolSirola** [comment]
Also Sir I dont know why I am unable to create a new issue ( after I am creating a issue ) summit new issue button is not working.

**Pull request closed without merging**
