### PR TITLE
Arithmetic Operators on Integers ( Add, Sub, Mul, Div )

### PR DESCRIPTION
**Pull request by Sanitya7**
## Description

Adding the program dealing with basic arithmetic operators on integers under the beginner level of Solidity Pathshala

Fixes #<35>

## Type of change

- [x] Add a new project

## Domain of Contribution

- [x] Project using only Solidity

- [x] Project Test on the Remix IDE

## Checklist ✓

- [x] l have performed a self-review of my own code or work.

- [x] I'm SSOC'22 contributor

## Screenshots/Gif (Recommended)
Sum_of_num
division_of_num
Product_of_num
sub_of_num

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
@Sanitya7  the format of the folder is wrong . U have to make the folder  of the specific name like **(Level0->Add -> Add.sol , README.md )**
Folow this folder structure . and please maintain the readme for each 
Thank u

**Comment by Sanitya7** [comment]
Thanks, I will correct it 👍

**Comment by Vikash-8090-Yadav** [comment]
> Thanks, I will correct it +1

??

**Comment by Sanitya7** [comment]
I am unable to do it in the manner which you said, since this is my first github project. 
Can the mentor from SSOC, assist me for the same ?

**Comment by Vikash-8090-Yadav** [comment]
> I am unable to do it in the manner which you said, since this is my first github project. Can the mentor from SSOC, assist me for the same ?
Dm me on the discord

**Comment by Vikash-8090-Yadav** [comment]
@Sanitya7 are u still working on this issue ?

**Comment by Sanitya7** [comment]
I hav edone this issue, but I am facing issue in making the PR, the mentor is not responding for the same !

**Comment by Vikash-8090-Yadav** [comment]
Dm me on discord !and the mentor is @AnmolSirola now contact him

**Comment by Vikash-8090-Yadav** [comment]
@Sanitya7  any updates ??

**Comment by Sanitya7** [comment]
I wasn't well, got swelling in Liver, and was on rest for a week, So it got delayed, 
I interacted with Anmol, the file is prepared, along with this I prepared an intermediate level file for if-else statement, will be adding it tomorrow. 

thanks for understanding, apologies from my end.

**Comment by Vikash-8090-Yadav** [comment]
No problem . Take care ! @Sanitya7

**Pull request closed without merging**
