### PR TITLE
Stack Implementation Using Solidity

### LINKED ISSUE #153: Stack
### Project title
Stack Implementation

### Project Description
Stack Implementation using Remix

### Domain
Solidity

### Are you contributing under any open-source program?
Hacktobefest

### PR DESCRIPTION
**Pull request by anishaga**
## Description

# Smart Contract "Stack Implementation" in Remix-IDE

## Stack
Stack is a linear data structure which follows a particular order in which the operations are performed. The order may be LIFO(Last In First Out) or FILO(First In Last Out). Stacks are used to implement functions, parsers, expression evaluation, and backtracking algorithms.

image

## Smart Contracts
Smart contracts are contracts that execute themselves. The Remix is an Integrated Development Environment (IDE) for creating smart contracts in Solidity. The Solidity code can be written, compiled, and debugged using the IDE.

Fixes #153 

## Type of change
- `[x]` Add a new project

- [] Modified or enhanced the existing projects

- [] Improve the readme of any project

## Domain of Contribution
- `[x]` Project using only Solidity

- [] Project using only Javascript

- [] Project using only Python

- [] Project Test on the Remix IDE

- [] Mention below if project uses other language and ide .

## Checklist ✓

- `[x]` l have performed a self-review of my own code or work.

- `[x]` My changes generate no new warnings

## Screenshots
image
- pop(): Will remove the element present at the top of the stack
- push(): Add a new element at the top of the stack
- getSize(): Tells the current size of the stack
- top(): Returns the top of the stack

### CODE REVIEW

**Comment by Vikash-8090-Yadav** [comment]
Below the image please explain about the function and their work

**Comment by Vikash-8090-Yadav** [comment]
Creat a heading About and explaim about this project in a line or two

**Comment by anishaga** [comment]
> Creat a heading About and explaim about this project in a line or two

@Vikash-8090-Yadav  I've made the required changes

**Comment by Vikash-8090-Yadav** [comment]
Great Looking forward to see more contribution from your side .

**Pull request merged**
